services:

  web:
    build: 
      context: .
      dockerfile: ./docker/python.Dockerfile
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./src:/app:delegated
    expose:
      - 8000
    env_file:
      - .env
    restart: always


  nginx:
    image: nginx:latest
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d/default.conf
      - ./src/static:/static:delegated
      - ./src/media:/media:delegated
      - ./docker/certbot/www:/var/www/certbot:ro
      - ./docker/certbot/conf:/etc/letsencrypt
    ports:
      - "${DOCKER_HTTP_PORT}:80"
      - "${DOCKER_HTTPS_PORT}:443"
    env_file:
      - .env
    restart: always
    depends_on:
      - web

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password

  certbot:
    image: certbot/certbot    
    volumes:
      - ./docker/certbot/www/:/var/www/certbot/:rw
      - ./docker/certbot/conf/:/etc/letsencrypt/:rw  

volumes:
  postgres_data: