services:

  web:
    build: 
      context: .
      dockerfile: ./docker/python.Dockerfile
    command: gunicorn ${DJANGO_PROJECT_NAME}.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./src:/app:delegated
    expose:
      - 8000
    env_file:
      - .env
    restart: always


  nginx:
    image: nginx:latest
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d/default.conf
      - ./src/static:/static:delegated
      - ./src/media:/media:delegated
      - ./docker/certbot/www:/var/www/certbot:ro
      - ./docker/certbot/conf:/etc/letsencrypt
    ports:
      - "${DOCKER_HTTP_PORT}:80"
      - "${DOCKER_HTTPS_PORT}:443"
    env_file:
      - .env
    restart: always
    depends_on:
      - web

  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_DATABASE}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  # certbot:
  #   image: certbot/certbot    
  #   volumes:
  #     - ./docker/certbot/www/:/var/www/certbot/:rw
  #     - ./docker/certbot/conf/:/etc/letsencrypt/:rw  

volumes:
  pgdata: